services:
  app:
    image: bloglist-front
    build:
      context: ./bloglist-frontend
      dockerfile: Dockerfile
    container_name: front-end

  server:
    image: bloglist-back
    build: 
      context: ./bloglist-backend
      dockerfile: Dockerfile

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server